version: '3.1'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./cmd/server/app.rsa:/app.rsa
      - ./cmd/server/app.rsa.pub:/app.rsa.pub
  db:
    image: postgres
    environment:
      #POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      #POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/initdb.sql
