global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s

#alerting

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: muzio
    static_configs:
      - targets: ['server:8080']